### ISSUE TITLE
DB

### ISSUE THREAD

**Issue by RedsAnDev** [STB1019/Flutter-AppRing#5]
The goal to achieve is a simple way to save more entities and respective relations.

**Comment by RobertoFilippini** [comment]
Mentre l'applicazione compila sul mio computer, rilevo il seguente errore:
DatabaseException(no such table: task(code 1 SQLITE_ERROR);, while compiling: SELECT * FROM task) sql 'SELECT * FROM task' args[]}

**Comment by RedsAnDev** [comment]
Ciao Roberto,
a quanto pare in quel momento nel database non "trova" la tabella task.
Per risolvere velocemente il problema, puoi "wrappare" con un try except ed in caso di errore, avviare la procedura di creazione tabella.
